name: license check

on:
  push:
    branches: [main]
  pull_request_target:
    types: [labeled]

permissions:
  contents: read

jobs:
  build_pr_license:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'safe to test')
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install gurobipy
    - shell: bash
      id: write-license
      env:
        LICENSE: ${{ secrets.LICENSE   }}
      run: |
        echo "$LICENSE" > $PWD/gurobi.lic
        echo "grb_license_file=$PWD/gurobi.lic" >> $GITHUB_OUTPUT
    - name: check license
      env:
        GRB_LICENSE_FILE: ${{ steps.write-license.outputs.grb_license_file }}
      run: |
        python -c "import os; print(['WLSACCESSID' in line for line in open(os.environ['GRB_LICENSE_FILE'])])"
    - name: run gurobi
      env:
        GRB_LICENSE_FILE: ${{ steps.write-license.outputs.grb_license_file }}
      run: |
        python -c "import gurobipy as gp; gp.Env()"
